version: "3.8"
services:
  app:
    container_name: app-dev
    image: app-dev:latest
    build:
      context: ./app/
      target: development
    volumes:
      - ./app/:/app/
    ports:
      - 3000:3000
  api:
        container_name: api-dev
        image: api-dev:latest
        build: ./api/
        volumes: 
            - ./api/:/usr/src/app/
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
      